/**
 * 生成物と手書きの区別（T-140）の単体テスト。
 *
 * 誤って手書きを生成物と判定すると、**読むべき変更が畳まれて見えなくなる**。
 * そこがこの機能の唯一の危険なので、判定が広がりすぎないことを重点的に押さえる。
 *
 *   node --test extensions/nimbus/out/test
 */
import * as assert from 'assert';
import { test } from 'node:test';
import { hasGeneratedHeader, isGenerated, isGeneratedPath, summarizeGenerated } from '../core/generated';
import { formatSummary, summarizeDiff } from '../core/diffSummary';

test('名前で分かる生成物を拾う', () => {
	assert.deepStrictEqual(
		[
			'lib/model.g.dart',
			'lib/model.freezed.dart',
			'src/api.pb.go',
			'src/schema_pb2.py',
			'pubspec.lock',
			'package-lock.json',
			'app.min.js',
			'types/index.d.ts'
		].map(isGeneratedPath),
		[true, true, true, true, true, true, true, true]
	);
});

test('置き場所で分かる生成物を拾う', () => {
	assert.deepStrictEqual(
		['node_modules/x/index.js', 'ios/Pods/Foo.h', 'build/out.js', 'src/__generated__/q.ts'].map(isGeneratedPath),
		[true, true, true, true]
	);
});

test('手書きを生成物と間違えない（ここを誤ると読むべき変更が消える）', () => {
	assert.deepStrictEqual(
		[
			'lib/model.dart',
			'src/generator.ts',
			'src/buildRunner.ts',
			'docs/generated-code.md',
			'src/core/generated.ts'
		].map(isGeneratedPath),
		[false, false, false, false, false]
	);
});

test('冒頭の印を読む。本文中の言及は拾わない', () => {
	assert.strictEqual(hasGeneratedHeader('// GENERATED CODE - DO NOT MODIFY BY HAND\nconst a = 1;'), true);
	assert.strictEqual(hasGeneratedHeader('/** @generated */\nexport const x = 1;'), true);
	assert.strictEqual(hasGeneratedHeader('// Code generated by protoc. DO NOT EDIT.'), true);
	// 6 行目以降の言及は見ない（本文で生成物の話をしているだけのファイルを畳まない）
	assert.strictEqual(hasGeneratedHeader('a\nb\nc\nd\ne\n// GENERATED CODE'), false);
});

test('名前で決まらないときだけ中身を見る', () => {
	assert.strictEqual(isGenerated('lib/thing.dart'), false);
	assert.strictEqual(isGenerated('lib/thing.dart', '// GENERATED CODE - DO NOT MODIFY'), true);
	assert.strictEqual(isGenerated('lib/thing.g.dart'), true);
});

test('畳んだ件数と行数をまとめる', () => {
	assert.strictEqual(
		summarizeGenerated([{ path: 'a.g.dart', added: 10, removed: 2 }, { path: 'b.g.dart', added: 5, removed: 0 }]),
		'生成物 2 ファイル（+15 −2）— 中身は畳んでいます'
	);
	assert.strictEqual(summarizeGenerated([]), '');
});

test('差分の要約では生成物を畳み、手書きだけを展開する', () => {
	const diff = [
		'diff --git a/lib/model.g.dart b/lib/model.g.dart',
		'+export function generatedThing(): void {}',
		'diff --git a/lib/model.dart b/lib/model.dart',
		'+export function handWritten(): void {}'
	].join('\n');
	const files = summarizeDiff(diff);
	assert.deepStrictEqual(
		files.map((f) => [f.path, f.generated]),
		[['lib/model.g.dart', true], ['lib/model.dart', false]]
	);
	const out = formatSummary(files);
	// 手書きの export は見出しに出る
	assert.ok(out.includes('足した `function handWritten`'), out);
	// 生成物の export は「外から見える変化」に混ぜない（数十件あると埋もれる）
	assert.ok(!out.includes('generatedThing'), out);
	// ただし隠さない。件数と名前は出す
	assert.ok(out.includes('## 生成物'), out);
	assert.ok(out.includes('生成物 1 ファイル'), out);
	assert.ok(out.includes('lib/model.g.dart'), out);
	// 合計の行数には生成物も含める（変更全体の大きさは正しく伝える）
	assert.ok(out.includes('2 ファイル・+2 −0'), out);
});
