/**
 * ロックファイル差分の翻訳（T-119）の単体テスト。
 *
 * いちばん怖いのは**メジャー更新を見落とすこと**なので、並び順と分類を重点的に押さえる。
 */
import * as assert from 'assert';
import { test } from 'node:test';
import { bumpKind, diffLocks, parseLock, parsePackageLock, parsePubspecLock, renderLockDiff } from '../core/lockDiff';

const pubspec = `# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
    source: hosted
    version: "1.2.0"
  path:
    dependency: transitive
    source: hosted
    version: "1.9.0"
sdks:
  dart: ">=3.4.0 <4.0.0"
`;

test('pubspec.lock から名前と版を取り出す（sdks は含めない）', () => {
	assert.deepStrictEqual([...parsePubspecLock(pubspec)], [['http', '1.2.0'], ['path', '1.9.0']]);
});

test('package-lock.json から名前と版を取り出す（node_modules を剥がす）', () => {
	const json = JSON.stringify({
		packages: {
			'': { version: '1.0.0' },
			'node_modules/left-pad': { version: '1.3.0' },
			'node_modules/@scope/pkg': { version: '2.0.1' }
		}
	});
	assert.deepStrictEqual([...parsePackageLock(json)], [['left-pad', '1.3.0'], ['@scope/pkg', '2.0.1']]);
});

test('知らない形式・壊れた中身では空を返す（黙って落ちない）', () => {
	assert.deepStrictEqual(
		[parseLock('yarn.lock', 'whatever').size, parsePackageLock('{ 壊れている').size],
		[0, 0]
	);
});

test('上がり方を分類する（数字で始まらないものは判定しない）', () => {
	assert.deepStrictEqual(
		[
			bumpKind('1.2.0', '2.0.0'),
			bumpKind('1.2.0', '1.3.0'),
			bumpKind('1.2.0', '1.2.1'),
			bumpKind('git-abc', 'git-def')
		],
		['major', 'minor', 'patch', 'other']
	);
});

test('増減と更新を拾い、メジャーを先頭に並べる', () => {
	const before = new Map([['a', '1.0.0'], ['b', '1.0.0'], ['gone', '0.1.0']]);
	const after = new Map([['a', '2.0.0'], ['b', '1.0.1'], ['new', '0.0.1']]);
	const diff = diffLocks(before, after);
	assert.deepStrictEqual(
		{
			changed: diff.changed.map((c) => `${c.name}:${c.kind}`),
			added: diff.added.map((a) => a.name),
			removed: diff.removed.map((r) => r.name)
		},
		{ changed: ['a:major', 'b:patch'], added: ['new'], removed: ['gone'] }
	);
});

test('版に変化が無ければ、そう書く（整形だけの差分を騒がない）', () => {
	const same = new Map([['a', '1.0.0']]);
	assert.ok(renderLockDiff(diffLocks(same, same), 'pubspec.lock').includes('版の変化はありません'));
});

test('メジャー更新は「先に見るべきもの」として別に出す', () => {
	const text = renderLockDiff(
		diffLocks(new Map([['a', '1.0.0']]), new Map([['a', '2.0.0']])),
		'pubspec.lock'
	);
	assert.deepStrictEqual(
		['先に見るべきもの（メジャー更新）', '**a** `1.0.0` → `2.0.0`', 'うちメジャー **1**'].map((s) => text.includes(s)),
		[true, true, true]
	);
});
