/**
 * 生成物と手書きの区別（tasks.md T-140）。
 *
 * `build_runner` を回すと `*.g.dart` と `*.freezed.dart` が何十ファイルも動く。
 * 差分の中でそれが手書きのコードと同じ重みで並ぶと、**読むべき数行が埋もれる**。
 * 生成物は「動いた」ことだけ分かればよく、中身を読む必要はほとんど無い。
 *
 * ただし**隠さない。** 畳むだけで、件数は必ず見せる。生成物のつもりで手書きを
 * 畳んでしまう誤判定はありえるし、生成物が「動いていないこと」に気づきたい場面もある。
 *
 * VS Code に依存しないので単体で検証できる。
 */

/** 名前で分かる生成物。拡張子とファイル名の規約 */
const GENERATED_NAME = [
	/\.g\.dart$/,
	/\.freezed\.dart$/,
	/\.gr\.dart$/,
	/\.config\.dart$/,
	/\.gen\.[jt]sx?$/,
	/\.generated\.[jt]sx?$/,
	/\.d\.ts$/,
	/\.pb\.(go|ts|js|dart)$/,
	/_pb2(_grpc)?\.py$/,
	/\.designer\.cs$/,
	/\.min\.(js|css)$/,
	/^(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|pubspec\.lock|Cargo\.lock|Gemfile\.lock|poetry\.lock|composer\.lock|go\.sum)$/
];

/** 置き場所で分かる生成物 */
const GENERATED_DIR = /(^|\/)(node_modules|Pods|\.dart_tool|build|dist|out|coverage|__generated__|generated|vendor)\//;

/**
 * 中身の先頭に書かれる印。ツールごとに言い回しが違うので広めに拾う。
 * 先頭のほうにしか書かれないので、**渡すのは冒頭だけでよい**。
 */
const GENERATED_HEADER =
	/(GENERATED CODE|DO NOT (EDIT|MODIFY)|@generated\b|Code generated by|autogenerated|auto-generated|This file was automatically generated)/i;

/** ファイル名・置き場所だけで判断する */
export function isGeneratedPath(filePath: string): boolean {
	const path = filePath.replace(/\\/g, '/');
	const name = path.split('/').pop() ?? '';
	return GENERATED_DIR.test(path) || GENERATED_NAME.some((pattern) => pattern.test(name));
}

/** 冒頭の数行に「生成物」と書かれているか */
export function hasGeneratedHeader(head: string): boolean {
	// 印は先頭付近にしか書かれない。全文を見ると本文中の言及を拾ってしまう
	return GENERATED_HEADER.test(head.split('\n').slice(0, 5).join('\n'));
}

/**
 * 生成物かどうか。名前で決まらないときだけ中身を見る。
 * @param head ファイル（または差分）の冒頭。省略すると名前だけで判断する
 */
export function isGenerated(filePath: string, head?: string): boolean {
	return isGeneratedPath(filePath) || (head !== undefined && hasGeneratedHeader(head));
}

/**
 * 生成物に対して「代わりにどれを直すのか」（tasks.md T-139）。
 *
 * 生成物を直接書き換えても、次に生成ツールを回した瞬間に消える。
 * **消えることより、消えたと気づかないまま先に進むほうが損害が大きい。**
 * だから「直しても無駄です」ではなく、**代わりに直す先を名指しする**。
 */
const SOURCE_OF: { pattern: RegExp; replacement: string }[] = [
	// build_runner（Flutter / Dart）: model.g.dart / model.freezed.dart → model.dart
	{ pattern: /\.(g|freezed|gr|config)\.dart$/, replacement: '.dart' },
	// protobuf: api.pb.go / api.pb.ts → api.proto
	{ pattern: /\.pb\.(go|ts|js|dart)$/, replacement: '.proto' },
	{ pattern: /_pb2(_grpc)?\.py$/, replacement: '.proto' },
	// 生成された型定義: x.gen.ts / x.generated.ts → x.ts
	{ pattern: /\.(gen|generated)\.([jt]sx?)$/, replacement: '.$2' }
];

/** ロックファイルは「直す先」がファイルではなくコマンドなので、別に扱う */
const LOCK_ADVICE: { pattern: RegExp; advice: string }[] = [
	{ pattern: /(^|\/)package-lock\.json$/, advice: 'npm install で作り直します' },
	{ pattern: /(^|\/)pnpm-lock\.yaml$/, advice: 'pnpm install で作り直します' },
	{ pattern: /(^|\/)yarn\.lock$/, advice: 'yarn install で作り直します' },
	{ pattern: /(^|\/)pubspec\.lock$/, advice: 'flutter pub get で作り直します' },
	{ pattern: /(^|\/)Cargo\.lock$/, advice: 'cargo build で作り直します' },
	{ pattern: /(^|\/)go\.sum$/, advice: 'go mod tidy で作り直します' },
	{ pattern: /(^|\/)Gemfile\.lock$/, advice: 'bundle install で作り直します' },
	{ pattern: /(^|\/)(poetry|composer)\.lock$/, advice: '依存の管理コマンドで作り直します' }
];

/**
 * 代わりに直すべきファイル。分からなければ undefined。
 * **推測で別のファイルを名指ししない** — 間違った場所を直させるほうが害になる。
 */
export function sourceFileFor(generatedPath: string): string | undefined {
	const path = generatedPath.replace(/\\/g, '/');
	for (const { pattern, replacement } of SOURCE_OF) {
		if (pattern.test(path)) {
			return path.replace(pattern, replacement);
		}
	}
	return undefined;
}

/** そのファイルを作り直す手立て。ファイルなら名前、コマンドなら言い回し */
export function regenerationAdvice(generatedPath: string): string | undefined {
	const path = generatedPath.replace(/\\/g, '/');
	const lock = LOCK_ADVICE.find((entry) => entry.pattern.test(path));
	if (lock) {
		return lock.advice;
	}
	const source = sourceFileFor(path);
	return source ? `${source} を直してから、生成ツールを回し直します` : undefined;
}

/**
 * 元を直したら、生成物も作り直す（tasks.md T-141）。
 *
 * `model.dart` の `@freezed` を触ったのに `model.g.dart` を作り直し忘れると、
 * **型エラーではなく「古い実装が静かに動く」**という、いちばん気づきにくい壊れかたをする。
 * 直した瞬間に「作り直しますか」と聞けるように、対応づけと作り直しかたをここに置く。
 */

/** そのファイルから生成されうる名前（実在するかは呼び出し側が見る） */
export function generatedSiblingsOf(sourcePath: string): string[] {
	const path = sourcePath.replace(/\\/g, '/');
	const dart = /^(.*)\.dart$/.exec(path);
	if (dart && !isGeneratedPath(path)) {
		return ['g', 'freezed', 'gr', 'config'].map((kind) => `${dart[1]}.${kind}.dart`);
	}
	const proto = /^(.*)\.proto$/.exec(path);
	if (proto) {
		return ['pb.go', 'pb.ts', 'pb.dart', '_pb2.py'].map((suffix) =>
			suffix.startsWith('_') ? `${proto[1]}${suffix}` : `${proto[1]}.${suffix}`
		);
	}
	return [];
}

/** 生成物を作り直すコマンド。プロジェクトの形から決める */
export interface RegenerateCommand {
	command: string;
	/** なぜこれなのか。人が確かめられるようにする */
	reason: string;
}

/**
 * どの生成ツールを回すか。
 * **見つからなければ undefined。** 当てずっぽうのコマンドを走らせると、
 * 別のものを壊しかねない（`build_runner` が無いのに走らせる等）。
 *
 * @param files プロジェクト直下にあるファイル名（`pubspec.yaml` など）
 * @param manifest `pubspec.yaml` / `package.json` の中身。依存を見て決める
 */
export function regenerateCommandFor(files: readonly string[], manifest: string): RegenerateCommand | undefined {
	const has = (name: string): boolean => files.includes(name);
	if (has('pubspec.yaml')) {
		if (/\bbuild_runner\b/.test(manifest)) {
			return {
				command: 'dart run build_runner build --delete-conflicting-outputs',
				reason: 'pubspec.yaml に build_runner があります'
			};
		}
		// build_runner が無い Flutter プロジェクトでは、生成物はそもそも無い
		return undefined;
	}
	if (has('package.json')) {
		if (/"(prisma)"\s*:/.test(manifest)) {
			return { command: 'npx prisma generate', reason: 'package.json に prisma があります' };
		}
		if (/"(graphql-codegen|@graphql-codegen\/cli)"\s*:/.test(manifest)) {
			return { command: 'npx graphql-codegen', reason: 'package.json に graphql-codegen があります' };
		}
		// `npm run generate` があればそれを使う（プロジェクトが決めた入口を尊重する）
		if (/"generate"\s*:/.test(manifest)) {
			return { command: 'npm run generate', reason: 'package.json に generate スクリプトがあります' };
		}
		return undefined;
	}
	if (has('go.mod')) {
		return { command: 'go generate ./...', reason: 'go.mod があります' };
	}
	return undefined;
}

/** 畳んだときに出す 1 行。件数と行数だけは必ず見せる */
export function summarizeGenerated(files: readonly { path: string; added: number; removed: number }[]): string {
	if (files.length === 0) {
		return '';
	}
	const added = files.reduce((sum, file) => sum + file.added, 0);
	const removed = files.reduce((sum, file) => sum + file.removed, 0);
	return `生成物 ${files.length} ファイル（+${added} −${removed}）— 中身は畳んでいます`;
}
